
###Variable holding the port
@API = http://localhost:3000



### tesing the server
GET {{API}}


############### AUTH ROUTES ###############

### Register a user (client/mechanic)
POST {{API}}/auth/register
content-type: application/json

{
    "full_name":"Gear Guru",
    "email":"gearguru@gmail.com",
    "contact_no":"0895674312",
    "location":["Pretoria"],
    "password":"123456",
    "role":"mechanic"
}



### Login user (client/mechanic)
POST {{API}}/auth/login
content-type: application/json

{
    "email":"k@k.com",
    "password":"123456"
}



############### MECHANIC ROUTES ###############

### Create mechanic profile
POST {{API}}/mech/create
content-type: application/json

{
    "_id":"65d5cc628f56c95a13096a2e",
    "bio":"I am located in Pretoria & I fix cars, you can trust me.",
    "language":["English", "Venda", "Swahili"],
    "speciality":"repair body parts",
    "service_fee":"500"
}



### get all mechanics
GET {{API}}/mech/all



### get one mechanics
GET {{API}}/mech/one/65d338996de10e4f874d4106



### update appointment status
PUT {{API}}/mech/app/status/65d3e369f71606466b4f3bca
content-type: application/json

{
    "status":"accepted"
}



### mechanic generate invoice
POST {{API}}/mech/invoice
content-type: application/json

{
    "_appointment":"65d3e369f71606466b4f3bca",
    "price": 800
}




############### CLIENT ROUTES ###############

### add a car
POST {{API}}/client/add
content-type: application/json

{
    "_id":"65d522a5916e91a452283a03",
    "make":"Renault",
    "model":"Clio",
    "registration":"G4H5J6 GP",
    "fuel_type":"petrol"
}



### get all cars for a specific client
GET {{API}}/client/all/65d522a5916e91a452283a03



### get one cars for a specific client
GET {{API}}/client/one/65d3cfa3d9cdf447b7ab74ab



### add aappointment
POST {{API}}/client/app/create
content-type: application/json

{
    "_client":"65d33bae6de10e4f874d4109",
    "_car":"65d3cfa3d9cdf447b7ab74ab",
    "_mechanic":"65d338996de10e4f874d4106",
    "service_type":"painting",
    "details":"want to get a new paint flauds happened",
    "date_time":"16/02/2024 12:00"
}



### get all appointments for a specific client
GET {{API}}/client/app/all/65d33bae6de10e4f874d4109




### get one appointment for a specific client
GET {{API}}/client/app/one/65d3de827e5dded9b8383e96