
###Variable holding the port
@API = http://localhost:3000



### tesing the server
GET {{API}}



### Register a user (client/mechanic)
POST {{API}}/auth/register
content-type: application/json

{
    "full_name":"Road Rover",
    "email":"roadrover@gmail.com",
    "contact_no":"0123456789",
    "location":["Midrand"],
    "password":"rover1234",
    "role":"client"
}



### Login user (client/mechanic)
POST {{API}}/auth/login
content-type: application/json

{
    "email":"gearguru@gmail.com",
    "password":"guru1234"
}



### Create mechanic profile
POST {{API}}/mech/create
content-type: application/json

{
    "_id":"65d338996de10e4f874d4106",
    "bio":"I am located in Joburg & I fix cars, you can trust me.",
    "language":["English", "Zulu", "Pedi"],
    "speciality":"exterior body parts",
    "service_fee":"500"
}